name: Build
on: [push]
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: pip install pyinstaller pywinauto
      - name: Build
        run: pyinstaller --onefile --windowed program.py
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Program_Dosyasi
          path: dist/program.exe
